### ISSUE TITLE
Email Confirmation label ":"

### ISSUE THREAD

**Issue by greyskymedia** [nuevephp/formz#16]
Looks like there system adds in :'s. Since the output doesn't also include :'s there's two in the form fields.

**Comment by silentworks** [comment]
That is a weird one, I haven't had that issue on my setup. Can you test this on another site and let me know if its the same result please.

**Comment by greyskymedia** [comment]
it's in the confirmation form. The [[+fields]] call builds the email responder and inserts :'s after the label.

**Comment by silentworks** [comment]
This is now solved, this option will be removed in the next release.
