### ISSUE TITLE
fiar

### ISSUE THREAD

**Issue by greyskymedia** [nuevephp/formz#18]
Need ability to designate a field as the "fiarToField" field so fiar can work

**Comment by greyskymedia** [comment]
It'd be great to be able to set fiar settings (all available honestly) within the FORM settings. Not in the TV, that way we don't need multiple TV's to manually set the fiar settings in the file

**Comment by greyskymedia** [comment]
I just learned that because of the way [[+actions]] is built i can't insert the fiar call without editing the php for the selected send method. I think fiar support is pretty critical. Any way to bump this up the request list?

**Comment by silentworks** [comment]
Would you be happy for this to be two separate hooks? [[+dbsave]],[[+email]]

**Comment by greyskymedia** [comment]
Absolutely!

Jamison Mergens
916.234.0040

On Nov 12, 2012, at 4:45 PM, Andrew Smith notifications@github.com wrote:

Would you be happy for this to be two separate hooks? [[+dbsave]],[[+email]]

**Comment by vierkantemeter** [comment]
Hi greyskymedia, just a quick question; did you get fiar to work with Formz?

For me I changed the formTpl to include the fiar info, and this is working so far. The autorespond email gets send, but the placeholders are not replaced. (it's just: [[+formName]] and [[+message]]. Did you get the values of the form to be send in the autorespond email? (btw: it's working fine in the recipient email). I also tried to call the FormItAutoResponder hook before the other hooks, this did not work.

**Comment by greyskymedia** [comment]
It’s been a WHILE, but, I actually don’t recall. I think my responder to the sender was always just a static “Thanks for the message”.

Jamison Mergens
web designer/developer

greyskymedia.com

p. (916) 234-0040
tf. (866) 722-GREY
f. (916) 209-8679

chat.
skype. jamison.mergens

mail & physical.

5875 Pacific St #E2

Rocklin, Ca 95677

**Comment by vierkantemeter** [comment]
Yeah, sorry just noticed your last reply was 9 months ago. Thanks anyway!

**Comment by greyskymedia** [comment]
No worries… shoot me an email really quick… jamison@greyskymedia.com
