### ISSUE TITLE
View submissions when saved to db

### ISSUE THREAD

**Issue by greyskymedia** [nuevephp/formz#19]
The fields are showing in reverse order

**Comment by silentworks** [comment]
Can you reorder them? I tested and this was working fine for me.

**Comment by greyskymedia** [comment]
they're in the right order to display on the front end, it's the email and view db where they're reversed. If i reordered them then the front end would be backwards

**Comment by silentworks** [comment]
Yes I see what you mean, I didn't really think it would matter to the user the order of the fields in the email and in the view db. But now that you have raised this, I will look into making sure the order remains consistent.
