### ISSUE TITLE
Form does not render only submit button.

### ISSUE THREAD

**Issue by terrybarth** [nuevephp/formz#22]
This looks really cool.  Thank you!

I just installed Formz and followed the instructions to setup a form. I created a name field, email field, text area and a check box, added validation messages etc. I setup the TV using formz for both input type and output type.

However the only thing that renders on the front-end is the submit button. 

I did notice there are two additional fields on the output options on the tv: Form Template and Form Field Template. I assume those are option so I left them blank.

This is what I see with firebug:

<p>
<code> </code>
</p>

<form class="form " method="post" action="">
<code>
<fieldset> </fieldset>
<div class="actions">
<input class="btn primary" type="submit" value="Send" name="submit">
</div>
</code>
</form>

<p></p>

Can you tell me what I did wrong?

Thanks.

**Comment by greyskymedia** [comment]
You put the tv call in the content right? Are you not caching [[!*form]]. Your image isn't pulling over either

**Comment by terrybarth** [comment]
Thanks for the fast response. Yes. tv call is in content like this:  [[*formz]]  The name of the tv is formz. I assume this name is not a problem. What image are you referring to?

**Comment by silentworks** [comment]
Please make sure you are calling it uncached [[!*form]], I will update the docs later on today.

**Comment by terrybarth** [comment]
Hmmm, no change. I cleared the cache and flushed permissions. Any other ideas?

I can pm you a login if you'd like to look more closely.

**Comment by silentworks** [comment]
Did you update from a previous install? Is there a chunk called formzTpl? I am currently out but send me login details and I will have a look later.

**Comment by terrybarth** [comment]
This is a new install via package install. There are three chunks in the Formz category: emailTpl, fieldTpl, formTpl.  There is no formzTpl.  To what address shall I send login info?

Thank you!

**Comment by silentworks** [comment]
Send to me at easylancer@gmail.com.

**Comment by greyskymedia** [comment]
Did you get this working?

**Comment by terrybarth** [comment]
No change. I sent the login info to you about an hour ago.

**Comment by silentworks** [comment]
Terry as stated before I am out but will take a look when I get back home.

**Comment by terrybarth** [comment]
Great.  It's not urgent.  Thank you!

**Comment by greyskymedia** [comment]
My kiddo is taking a nap in 10m, I'd be happy to look too if you want. Jamison@greyskymedia.com

Jamison Mergens
916.234.0040

On Sep 22, 2012, at 12:11 PM, terrybarth notifications@github.com wrote:

Great. It's not urgent. Thank you!

**Comment by silentworks** [comment]
Hi Terry, it would seem you have done almost everything, the only thing you missed out is FormItFastPack, I will install this and get it up and running for you.

Also remember for checkbox, radio and select we are using the MODX standard pipe | symbol to create multiple options.

**Comment by greyskymedia** [comment]
I was going to suggest that! Glad you sorted it.

**Comment by terrybarth** [comment]
Thank you so much!

Yes, (slap forehead)  I saw that in the requirements, I assumed that the
package installed the FormItFastPack too.   I never even checked on it.

Thank you!

http://www.terrybarthdesign.com/?utm_source=My%2Bgmail%20signature&utm_medium=email&utm_campaign=My%2Bgmail%20signature
www.terrybarthdesign.comhttp://www.terrybarthdesign.com/?utm_source=My%2Bgmail%20signature&utm_medium=email&utm_campaign=My%2Bgmail%20signature
Terry Barth Design Website Services
612-859-2453
For web sites that work as hard as you do!
Contact Me [image: Linkedin] http://www.linkedin.com/in/terrybarth[image:
Facebook] http://www.facebook.com/TerryBarthDesign
