### ISSUE TITLE
Adjusting the email

### ISSUE THREAD

**Issue by friedaweb** [nuevephp/formz#27]
It would be great if it is possible to format the email name, email and subject with the formit call:
emailFromName=`[[+field#]]
emailFrom=`[[+field#]]
emailSubject=`[[+field#]]

So, you immediately know who sent the email and can use the email for your reply.

It is a great addon and this enhancement will make it do the job for me.

**Comment by silentworks** [comment]
I have added a fix for this and will push in the next release [rc2] of Formz. You will be able to do 

```
&emailFromName=`[[+field.field#]]`
&emailFrom=`[[+field.field#]]`
&emailSubject=`[[+field.field#]]`
```

**Comment by friedaweb** [comment]
```
Hi Andrew,
    Great, thanks!I am looking forward
      to the next release!
  Kind regards,
```

Frieda Bos Webdesign & Support
Letters Lodge South, Strathlachlan, Argyll, PA27 8BZ, Scotland (UK), tel. 01369 860272
Email: frieda@friedaweb.co.uk
Website: www.friedaweb.co.uk
      On 10/11/2012 15:38, Andrew Smith wrote:

```
  I have added a fix for this and will push in the next release
    [rc2] of Formz. You will be able to do 
  &emailFromName=`[[+field.field#]]`
```

&emailFrom=`[[+field.field#]]`
&emailSubject=`[[+field.field#]]`

```
    —
    Reply to this email directly or view
      it on GitHub.
```
