### ISSUE TITLE
Specify redirect page

### ISSUE THREAD

**Issue by PeterKnightDigital** [nuevephp/formz#28]
Would like to be able to specify the &redirectTo=ID in the form builder

**Comment by greyskymedia** [comment]
second

**Comment by PeterKnightDigital** [comment]
Just showed Formz to a client and they loved it but the hard coded redirect was an issue. Any sign of an update?

**Comment by silentworks** [comment]
At the moment, this will be in the next version, at the moment that won't be ready until in around 2 weeks. Did you try the suggestion I gave on the forum?

Create a TV called redirect and add the param to the Formit call in &redirectTo=`[[*redirect]]`, at this point you can point to a resource you already have by id or if you created your TV as a resource type TV then you will have a select list.

I hope this is helpful.

**Comment by PeterKnightDigital** [comment]
Yep - I am going to try this later next week. It's a great workaround for the moment. 
Many thanks for the update. Looking forward to it.
