### ISSUE TITLE
Submissions

### ISSUE THREAD

**Issue by PeterKnightDigital** [nuevephp/formz#29]
The Submissions UI has 3 columns: ID, Sent On and IP Address

I think it'd be very useful to have a 'from' column in there too. 99% of forms ask for a name so it'd be a nice feature to be able to locate a submission if there were 1000s.

**Comment by silentworks** [comment]
And what if my field is called something else? maybe 'who'? I think this is a area that will need some more user feedback to see how everyone is using Formz.

**Comment by markushh** [comment]
hi silentwork,

thank you for the extra!! it's exactly what i need. but i also want to change the submission-grid. i understand, that we need to know more about the use to do it generally. 

but can you tell me, where i can change the grid for my use by myself? i guess i need a hint to start ;)

**Comment by markushh** [comment]
ok, i just added the "fields" to the grid (and to the lexicon). 
/assets/components/formz/js/mgr/widgets/form/data/grid.js

...
,fields: ['id','senton','ip_address','name','fields']
...
...

{
            header: _('formz.submissions.fields')
            ,dataIndex: 'fields'
            ,width: 70
}

with a little customizing of the /core/components/formz/processors/mgr/formz/data/getlist.class.php i am lucky with my result.

thx and regards,
m.
