### ISSUE TITLE
no mail sent + error log

### ISSUE THREAD

**Issue by em-piguet** [nuevephp/formz#36]
on my modx 2.2.5 pl 

i get this error in my log 

fmzFormsDataFields: Attempt to set NOT NULL field label to NULL

and no mail is sent but mail is in the DB.

To correct this i had to UNCACHE the resource holding the form.

**Comment by silentworks** [comment]
Can you test this with the new version on github? go to the repo and open the _packages directory you should see a rc2 there download that file and upload to your packages directory of MODX and install it in the manager. This should fix this issue.

**Comment by em-piguet** [comment]
Ok, i upgrade to the rc2 but it's the same behaviour: no mail sent when resource is cached.
btw, the confirmation messages are gone when submitting the form. 
Don't know if it's related but i use smtp to send emails on this host. 
btw2 : this component is awesome, thx for your work.

**Comment by silentworks** [comment]
I seem to be able to send email whether cached or uncached. There is a issue in that rc2 update to do with the new redirect code I added in, hence why your message is no longer showing up. I am making a hotfix now.

**Comment by silentworks** [comment]
Pull down the update of rc2 off here again and try. You might need to remove redirect_to from your formz_forms database table manually.
