### ISSUE TITLE
CSV export only returns 21 results

### ISSUE THREAD

**Issue by EdwardIII** [nuevephp/formz#45]
Whenever I export via CSV I only get 21 results even if more have been submitted.

I cracked open core/components/formz/processors/mgr/formz/data/export.class.php but couldn't see anything limiting the number of results.

I'm running:

MODx 2.2.6-pl 
Form 1.0.0 rc1

**Comment by EdwardIII** [comment]
I've come up with a temporary workaround for this, I made this edit to `assets/components/formz/js/mgr/workspace/form/data.js`:

```
@@ -27,6 +27,8 @@
                     ,params: {
                         action: 'mgr/formz/data/export'
                         ,formId: config.formId
+                        ,start: 0
+                        ,limit: 99999999
                     }
                     ,form: Ext.fly('frmDummy')
                     ,isUpload: true
```

I tried working directly on the connector and setting a high limit but it didn't seem to work, is there a more holistic solution to this problem?

**Comment by silentworks** [comment]
This has been fixed in RC2 which is due for release soon.

**Comment by silentworks** [comment]
This will be out in RC3 from Package Management.
