### ISSUE TITLE
Submitting form multiple times: field labels are not saved in db

### ISSUE THREAD

**Issue by vierkantemeter** [nuevephp/formz#46]
Thanks for this great addon! I'm experimenting with this component (rc2) and I find that when submitting a form multiple times (from same browser) the field labels only get saved in the DB and send in the email the first time. Only when I make the resource uncached, this does not happen (but that's not really an option). 

The formit call I use is uncached. The field values are always saved in the db and passed in the email, but as I said the labels are not. In the email they don't show up at all. Also, [[+formName]] is not available in the email after the first time submitting, it just shows the placeholder. When I submit the form for the first time it does work and shows the form name correctly. 

Clearing the browser cache/cookies does not help, clearing the modx cache does help. 
What could be the problem? Thanks for any pointers!

**Comment by silentworks** [comment]
As it stands you would have to use Formz uncached for it to work as desired, I haven't really done any work on it for some time now and not sure why its not working when its cached.

**Comment by vierkantemeter** [comment]
ok thanks Andrew, that's ok, I'll see if I can think of something myself!

**Comment by vierkantemeter** [comment]
I found a better fix for this than making the entire resource uncached: make the formz tv uncached, like this:

[[!*my_form]]

Seems to work, and my clients will understand it better than making the resource uncached.

**Comment by silentworks** [comment]
Great to know.
