### ISSUE TITLE
No fields in the frontend

### ISSUE THREAD

**Issue by exside** [nuevephp/formz#53]
based on the discussion here: http://forums.modx.com/thread/90951/modx-formz#dis-post-498269

I tried myself and couldn't get any fields to be shown in the frontend, the wrapper seems to be there, but the [[+fields]] placeholder seems to be empty...

![modx formz](https://cloud.githubusercontent.com/assets/445501/3027927/7cf48bb6-e027-11e3-80c6-a5b1c9528705.gif)

**Comment by silentworks** [comment]
You need to report this to the new owners of formz https://github.com/Adido/formz

**Comment by exside** [comment]
oh, sorry, done!
