### ISSUE TITLE
Form Builder doesn't save new forms

### ISSUE THREAD

**Issue by HarveyEV** [nuevephp/formz#6]
MODX 2.2.4 with new install and updated formit, ffp, and formz tested in FF, Chrome and IE8:

When attempting to create a new form, at the add fields stage, the UI shows "loading" but never releases the UI and no form is created.

**Comment by silentworks** [comment]
Hi HarveyEV, did you get this resolved in the end as it seem you closed the ticket?

**Comment by shabang** [comment]
Hello, 
I have got the same problem in modx 2.2.4 and 2.2.6. In chrome's console, i have this error : 

Uncaught SyntaxError: Unexpected token < ext-all.js:7
Ext.util.JSON.doDecode ext-all.js:7
(anonymous function) ext-all.js:7
Ext.extend.onStoreException index.php:178
h.Event.fire ext-all.js:7
h.Observable.fireEvent ext-all.js:7
(anonymous function) ext-all.js:7
h.Event.fire ext-all.js:7
h.Observable.fireEvent ext-all.js:7
Ext.extend.onRead ext-all.js:7
(anonymous function) ext-all.js:7
Ext.extend.handleResponse ext-all.js:7
f ext-base.js:7
m ext-base.js:7
(anonymous function) ext-base.js:7

**Comment by silentworks** [comment]
I will take a look into this, when does this happen? is it when trying to save a form or trying to retrieve a form?

**Comment by shabang** [comment]
I create my form, but i have this error when i try to add a field in my form.
I have already create one form with multiple field. I can retrieve this in my ressource. But in formz listing, i can't see this form, and i can't edit it.

**Comment by silentworks** [comment]
I am pushing a new version over the weekend retest this then.

**Comment by shabang** [comment]
thank's you !
