### ISSUE TITLE
confirmation email

### ISSUE THREAD

**Issue by greyskymedia** [nuevephp/formz#9]
my confirmation emails aren't showing the labels at all and is showing Sent from [[+formName]]: test... thoughts?

**Comment by silentworks** [comment]
I never had this issue before, I even setup a copy last night on someone elses server and they don't have this issue either. Have you tried setting this up on a different environment?

**Comment by greyskymedia** [comment]
I have, different server too...

**Comment by friedaweb** [comment]
I have the same issue on different servers. Just upgraded to 1.0.0 beta3 and still the same. Apart from that you are my hero by developing a user friendly form builder.

**Comment by silentworks** [comment]
You need to clear your cache, please do so a couple of times as MODX cache clearing seem to be problematic when it comes to clearing it.

**Comment by greyskymedia** [comment]
manually clear the cache in MODx (core, cache).... then clear your browser cache... THEN make sure your form call isn't cached [[!form]]... it SHOULD work then. I've verified this on 3 different sites that things are working great now.

**Comment by friedaweb** [comment]
```
Thanks for your prompt reply.
    Yes, that did the job!
  Kind regards,
```

Frieda Bos Webdesign & Support
Letters Lodge South, Strathlachlan, Argyll, PA27 8BZ, Scotland (UK), tel. 01369 860272
Email: frieda@friedaweb.co.uk
Website: www.friedaweb.co.uk
      On 19/09/2012 22:15, silentworks wrote:

```
  You need to clear your cache, please do so a couple of times as
    MODX cache clearing seem to be problematic when it comes to
    clearing it.

    —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by silentworks** [comment]
I am closing this one down.
